server:
    port: 8080



spring:
    session:
        store-type: none
    rabbitmq:
        host: 114.55.124.109
        port: 5672
        username: admin
        password: admin
        virtual-host: /
        listener:
            simple:
                max-concurrency: 20
                concurrency: 10
                prefetch: 5
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
            one:  #数据源1
                url: jdbc:mysql://106.12.26.186:3306/ticket?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=America/New_York&useSSL=false
                username: root
                password: 123456
            two: #数据源2
                url: jdbc:mysql://106.12.26.186:3307/ticket?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=America/New_York&useSSL=false
                username: root
                password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.agile.agiletest.pojo  # 注意：对应实体类的路径
    configuration:
        map-underscore-to-camel-case: true   #识别驼峰命名法


